big_brother/urls.py
from django.views.generic import DetailView, ListView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^student/', include('student.urls')),
    url(r'^company/', include('company.urls')),
)

company/urls.py
from django.views.generic import DetailView, ListView
from django.conf.urls import patterns, include, url

from student.models import Student
from student.models import Company
from student.models import Internship

urlpatterns = patterns('',
    # Company urls
    url(r'^$',
        ListView.as_view(
            queryset=Internship.objects.order_by('-id')[:5],
            context_object_name='internships_list',
            template_name='company/index.html')),    
            
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Company,
            template_name='company/company.html')),
            
    url(r'^(?P<pk>\d+)/edit/$', 'company.views.company_edit'),
    url(r'^(?P<pk>\d+)/save/$', 'company.views.company_save'),

    url(r'^notified/$','student.views.notified'),
    
    #internships urls
    url(r'^internship/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Internship,
            template_name='company/internship.html')),
            
    url(r'^(?P<pk>\d+)/internship/create$', 'student.views.internship_create'),    
            
    url(r'^(?P<pk>\d+)/internship/(?P<internship_id>\d+)/edit$', 'student.views.internship_edit'),
    url(r'^(?P<pk>\d+)/internship/(?P<internship_id>\d+)/save/$', 'student.views.internship_save'),

    #students pool urls
    url(r'^(?P<pk>\d+)/pool$',
        DetailView.as_view(
            model=Company,
            template_name='company/pool.html')),
    url(r'^(?P<pk>\d+)/pool/(?P<sk>\d+)/ping/$', 'company.views.pool_ping'),     
    
)

student/urls.py
from django.views.generic import DetailView, ListView
from django.conf.urls import patterns, include, url

from student.models import Student
from student.models import Company
from student.models import Internship

urlpatterns = patterns('',
    # student urls
    url(r'^$',
        ListView.as_view(
            queryset=Student.objects.order_by('sur_name'),
            context_object_name='student_list',
            template_name='student/index.html')),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Student,
            template_name='student/detail.html')),
    url(r'^(?P<pk>\d+)/edit/$',
        DetailView.as_view(
            model=Student,
            template_name='student/edit.html')),
    url(r'^json/$', 'student.views.get_students'),
    url(r'^(?P<fb_id>\d+)/experiences/$', 'student.views.get_student_experiences'),
    url(r'^(?P<fb_id>\d+)/projects/$', 'student.views.get_student_projects'),
    url(r'^create/$', 'student.views.student_create'),
    url(r'^save/$', 'student.views.student_save'),
)

student/models.py
from django.db import models

# Create your models here.

class App(models.Model):
    """
    """
    secret = models.CharField(max_length=32)
    app_id = models.IntegerField()

class School(models.Model):
    """
    """
    facebook_id = models.CharField(unique=True, max_length=20)
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class Project(models.Model):
    """
    Students' school project.
    """
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)

    def __unicode__(self):
        return self.name


class Subject(models.Model):
    """
    """
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)

    def __unicode__(self):
        return self.name


class Experience(models.Model):
    """
    Student's previous experiences (internship, summer jobs ...)
    """
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    date_start = models.DateField()
    date_end = models.DateField()

    def __unicode__(self):
        return self.name


class Student(models.Model):
    """
    """
    facebook_id = models.CharField(unique=True, max_length=20)
    first_name = models.CharField(max_length=200)
    sur_name = models.CharField(max_length=200)
    school = models.ForeignKey('School', null=True, blank=True)
    experiences = models.ManyToManyField('Experience', null=True, blank=True)
    projects = models.ManyToManyField('Project', null=True, blank=True)

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.sur_name)


class Company(models.Model):
    """
    Companies which are looking for applicants
    """
    facebook_id = models.CharField(primary_key=True, max_length=20)
    name        = models.CharField(max_length=200)
  
    def __unicode__(self):
        return self.name


class Internship(models.Model):
    """
    Internship posted by companies.
    """
    company     = models.ForeignKey('Company')
    title       = models.CharField(max_length=200)
    description = models.CharField(max_length=10000)
    tags        = models.CharField(max_length=200)
    applicants  = models.ManyToManyField('Student')
    active      = models.BooleanField(True)

    def __unicode__(self):
        return self.title

student/forms.py
from django.forms import ModelForm

from student.models import Student, Company, Internship


class StudentForm(ModelForm):
    class Meta:
        model = Student

class CompanyForm(ModelForm):
    class Meta:
        model = Company

class InternshipForm(ModelForm):
    class Meta:
        model = Internship

student/views.py
import json

from django.http import HttpResponse, HttpResponseRedirect
from django.template import Template, RequestContext
from django.shortcuts import render
from django.shortcuts import render_to_response, get_object_or_404


from forms import *
from models import *


def index(request):
    data = {"title": "Main"}
    return render(request, "main.html", data)


def student_create(request):
    """
    """
    return render_to_response(
        'student/student_create.html',
        context_instance=RequestContext(request))


def student_save(request):
    if request.method == 'POST':
        if 'id' in request.POST:
            student = Student.objects.get(pk=request.POST['id'])
            form = StudentForm(request.POST, instance=student)
        else:
            try:
                student = Student.objects.get(facebook_id=request.POST['facebook_id'])
            except Student.DoesNotExist:
                form = StudentForm(request.POST)
            else:
                form = StudentForm(request.POST, instance=student)

        if form.is_valid():
            student = form.save()  # vuln here, auth + check needed
            return HttpResponseRedirect('/student/' + str(student.id))

        return render_to_response(
            'student/student_create.html',
            {'errors': reduce(list.__add__, form.errors.values()),},
            context_instance=RequestContext(request))


def get_students(request):
    """
    Ajax call: get the list of students
    """
    names = ['%s %s' % (student.first_name, student.sur_name)
             for student in Student.objects.all()]
    return HttpResponse(json.dumps(names), mimetype='application/json')


def get_student_experiences(request, fb_id):
    """
    Ajax call: get the list of experiences
    """
    student = get_object_or_404(Student, facebook_id=fb_id)
    experiences = [exp.name for exp in student.experiences.all()]
    return HttpResponse(json.dumps(experiences), mimetype='application/json')


def get_student_projects(request, fb_id):
    """
    Ajax call: get the list of projects
    """
    student = get_object_or_404(Student, facebook_id=fb_id)
    projects = [p.name for exp in student.projects.all()]
    return HttpResponse(json.dumps(projects), mimetype='application/json')


# Create a new company
#def company_create(request):
#  company = Company.objects.create(name = request['name'])
#  return Company.objects.filter('id'=company.id)

def company_edit(request, pk):
    """
    """
    student = get_object_or_404(Company, facebook_id=pk)
#    import pdb; pdb.set_trace()
    return render_to_response(
        'company/company_edit.html',
        {
            'form': CompanyForm(instance=company),
            'company': company,
            },
        context_instance=RequestContext(request))
        
def company_save(request, pk):
    if request.method == 'POST':
        company = Company.objects.get(facebook_id=pk)
        form = CompanyForm(request.POST, instance=company)
        if form.is_valid():
            form.save()  # vuln here, auth + check needed
            return HttpResponseRedirect('/company/' + pk + '/edit')
    else:
        form = CompanyForm()

    return HttpResponseRedirect('/company/' + pk + '/edit')

# Create a new internship
def internship_create(request, pk):
  return HttpResponseRedirect('/company/' + pk + '/internship/1/edit')
#  internship = Internship.objects.create(title = request['title'], company = Company.objects.filter('id' = request['company']))
#  return edit_internship('id'=internship.id)

#  return HttpResponseRedirect('/company/' + internship.company.facebook_id + '/internship/' + internship.id + '/edit')

# View / Edit internship data

def internship_edit(request, pk,  internship_id=None):
    """
    """
    internship = get_object_or_404(Internship, id=internship_id)
#    import pdb; pdb.set_trace()
    return render_to_response(
        'company/internship_edit.html',
        {
            'form': InternshipForm(instance=internship),
            'internship': internship,
            },
        context_instance=RequestContext(request))
        
def internship_save(request, internship_id):
    if request.method == 'POST':
        internship = Internship.objects.get(id=internship_id)
        form = InternshipForm(request.POST, instance=internship)
        if form.is_valid():
            form.save()  # vuln here, auth + check needed
            return HttpResponseRedirect('/company/' + internship.company.facebook_id + '/internship/' + internship_id + '/edit')
    else:
        form = CompanyForm()

    return HttpResponseRedirect('/company/' + internship.company.facebook_id + '/internship/' + internship_id + '/edit')

# view a student profile
def view_student(request):
  pass

# Ona selected internship actions
def ping_students(request):
  pass

def notified(request):
  return HttpResponseRedirect('/company/104024606296679/')

templates/student/detail.html
{% extends "main.html" %}

{% load partial_template %}

{% block title %}{{ student.first_name }}{% endblock %}

{% block js %}
<script src="/static/js/detail_student.js"></script>
{% endblock %}

{% block content %}
<div id="student_infos">
  <!-- Student name -->
  <div>
    <img src="http://graph.facebook.com/{{student.facebook_id}}/picture?type=normal">
    <!-- <h2 id="second_page_student_name" style="float:right">{{student.first_name}} {{student.sur_name}}</h2> -->
    <h2 id="second_page_student_name">{{student.first_name}} {{student.sur_name}}</h2>
  </div>

  <div>
    <!-- School name  -->
    <img src="/static/img/mock-contact.png">
  </div>


</div>

<div class="span5" id="right_column">
<div id="student_internship_infos">
  <p class="looking_for">I'm looking for an internship from</p>

  <span id="intern_from" style="font-weight: bold;">{{internship_date_from}}</span> to <span id="intern_to" style="font-weight: bold;">{{internship_date_to}}</span>
</div>
<div style="text-align: center; margin-top: 32px;">
    <img src="/static/img/map.png" />
  </div>
</div>

<div id="add_section">
{% include 'partials/student/more_info.html' %}

{%for project in student.projects.all %}
    {% partial_template student/project.html project %}
{% endfor %}

{%for experience in student.experiences.all %}
    {% partial_template student/experience.html experience %}
{% endfor %}

{% endblock %}

templates/student/edit.html
{% extends "main.html" %}

{% load partial_template %}

{% block title %}{{ student.first_name }}{% endblock %}

{% block js %}
<script src="/static/js/detail_student.js"></script>
{% endblock %}

{% block content %}
<div id="student_infos">
<!-- Student name -->
<div>
  <h2 id="second_page_student_name" style="float:right">{{student.first_name}} {{student.sur_name}}</h2>
  <img src="http://graph.facebook.com/{{student.facebook_id}}/picture?type=normal">
</div>
<!-- School name  -->
 <div>
    {% partial_template school/student_detail.html student.school %}
</div>
<!-- Majors -->
 <div>
  <h3 id="second_page_majors">{{Majors}}</h3>
</div>
</div>

<div id="right_column">
<div id="student_internship_infos">
  <p class="looking_for">I'm looking for an internship from</p>

  <span id="intern_from" style="font-weight: bold;">{{internship_date_from}}</span> to <span id="intern_to" style="font-weight: bold;">{{internship_date_to}}</span>
</div>

<div id="news_feed">
  <h4>News Feed</h4>
  <ul class="bluesquare">
    <li>
      <span><a>Ronald</a> added you to the project <a id="truand">Bario Mros</a></span>
    </li>
    <li>
      <span><a >Ronald</a> added you to the school <a >Telecoms</a></span>
    </li>
    <li>
      <span>You are now  associated you to the school <a >Telecoms</a></span>
    </li>
  </ul>
</div>
</div>

<div id="add_section">
<!-- ADD a project -->
<div>
  <a id="add_project_button" class="btn btn-primary btn-large all_space add_button" >Add a school project</a>
  <div id="edit_project_section" class="edit_section" style="display: none;">
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="edited-inputProject">Project</label>
        <div class="controls">
          <input type="text" id="edited-inputProject" placeholder="Enter your project">
          <span class="with"> with <i id="friend_list" class="icon-user"></i></span>
          <input type="text" id="input_13" style="display:none">
        </div>

          <a id="save_project_button" class="btn btn-primary disabled save_button" >Save</a>
      </div>
      <div style="padding-left:400px; display:none;" id ="truand2">
          <p></p><p><b color="blue">Bario Mros</b> made with Ronald</p><p></p>
          <p style="margin-left:-200px">A super game with Bario Mros using python and personnal high quality textures</p>
        </div>
    </form>
  </div>
</div>

<!-- ADD an organization -->
<div>
  <a id="add_orga_button" class="btn btn-primary btn-large all_space" >Add a sorority</a>
  <div id="edit_orga_section" class="edit_section" style="display: none;">
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="edited-inputSorority">Sorority</label>
        <div class="controls">
          <input type="text" id="edited-inputSorority" placeholder="Enter your Sorority">
          <a id="save_orga_button" class="btn btn-primary disabled" >Save</a>
        </div>
      </div>

    </form>
  </div>
</div>

<!-- ADD a skill -->
<div>
  <a id="add_skill_button" class="btn btn-primary btn-large all_space" >Add a skill</a>
  <div id="edit_skill_section" class="edit_section" style="display: none;">
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="edited-inputSkill">Skill</label>
        <div class="controls">
          <input type="text" id="edited-inputSkill" placeholder="Enter your skill">
          <a id="save_skill_button" class="btn btn-primary disabled" >Save</a>
        </div>
      </div>

    </form>
  </div>
</div>

<!-- ADD an internship -->
<div>
  <a id="add_internship_button" class="btn btn-primary btn-large all_space" >Add an internship</a>
  <div id="edit_internship_section" class="edit_section" style="display: none;">
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="edited-inputInternship">Internship</label>
        <div class="controls">
          <input type="text" id="edited-inputInternship" placeholder="Enter your internship">
          <a id="save_internship_button" class="btn btn-primary disabled" >Save</a>
        </div>
      </div>

    </form>
  </div>
</div>

<!-- References -->
<div>
  <a id="add_references_button" class="btn btn-primary btn-large all_space" >View your references</a>
  <div id="edit_references_section" class="edit_section" style="display: none;">
    <form class="form-horizontal">
      <div class="control-group">
        <label class="control-label" for="edited-inputInternship" style="margin-left:-10px;margin-right:20px;"><b style="color:#0088bb; font-size : 1.5em;">Victor</b></label>
        We worked together on the Software project in first year, he was an amazing asset to our team, both skilled on calm, Loved to work with you guy !
      </div>

    </form>
  </div>
</div>

</div>

{% include 'partials/student/more_info.html' %}

{%for project in student.projects.all %}
    {% partial_template student/project.html project %}
{% endfor %}

{%for experience in student.experiences.all %}
    {% partial_template student/experience.html experience %}
{% endfor %}

{% endblock %}

templates/student/index.html
{% extends "main.html" %}

{% block title %}
Students list
{% endblock%}

{% block js %}
    <link href="/static/css/DT_bootstrap.css" rel="stylesheet" media="screen">
    <script src="/static/js/jquery.dataTables.min.js"></script>
    <script src="/static/js/main.js"></script>
    <script src="/static/js/DT_bootstrap.js"></script>
{% endblock %}

{% block content %}

<div align="center">
  <h3>
    <span style="font-weight: normal;">
      Students list
    </span>
  </h3>
  
  <div id="search_table">
    <form>
      <input type="text" name="Domain" placeholder="Domain">
      <input type="text" name="Schools" placeholder="Schools">
      <input type="text" name="Tags" placeholder="Tags">
      <input type="text" name="Majors" placeholder="Majors">
    </form>
  </div>

  <div id="main_table">
    <!-- <table id='search_table' class="table table-hover bordered-table zebra-striped"> -->
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
      <thead>
        <tr>
          <th>
              <input type="checkbox" name="checked_all" value="checked_all"> select all
          </th>
          <th>Surname</th>
          <th>First name</th>
          <th>School</th>
        </tr>
      </thead>

      <tbody>
        {% for student in student_list %}
          <tr>
            <td>
              <input type="checkbox"/>
            </td>
            <td>
              <a href="/student/{{student.id}}">
                {{ student.sur_name }}
              </a>
            </td>
            <td>
              <a href="/student/{{student.id}}">
                {{ student.first_name }}
              </a>
            </td>
            <td>
              <a href="/student/{{student.id}}">
                {{ student.school }}
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


<!--
window.open ('fenetre_popup.html')
-->


<div><button onclick="window.open('/company/notified')" >notify users</button></div>

{% endblock %}

templates/student/student_create.html
{% extends "main.html" %}

{% block title %}
Profile
{% endblock%}

{%block js%}
<script src="/static/js/main.js"></script>
{%endblock%}

{% block content %}

<div align="center">
  <h3>
    <span style="font-weight: normal;">
      Welcome <span id="welcome">{{ student.first_name }}</span>!
    </span>
  </h3>

  <div id="spoiler_container">
    <a id="landing_fb_connect" class="btn btn-primary btn-large" href="#">
      Use My Facebook Profile
    </a>

    <div id="spoiler_bottom">
      or
      <div id="enter_manually_div">
        <a href="#" id="enter_info_manually">
          enter your info manually
        </a>
      </div>

      <div style="text-align: center;">
        <i class="icon-chevron-down"></i>
      </div>

    </div>

  </div> <!-- end spoiler  -->

  <form action="/student/save/" method="post" class="form-horizontal">
    <div id="main_form" style="display: none;">
      <fieldset>
        <legend style="text-align:left">School Information</legend>
        {% csrf_token %}
        <input id="id_facebook_id" type="hidden" name="facebook_id" value="42" />
        <input id="id_first_name" type="hidden" name="first_name" value="Johm" />
        <input id="id_sur_name" type="hidden" name="sur_name" value="Doe" />

        <img id="school_picture" src="" style="float:right; margin-right:50px; margin-bottom:10px">
        <div style="float:left">
          <div class="control-group">
            <label class="control-label" for="inputSchool">School <i class="icon-book"> </i></label>
            <div class="controls">
              <input type="text" id="inputSchool" placeholder="Enter your school">
              <input type="hidden" name="school_facebook_id" value="42">
            </div>
          </div>

          <div class="control-group">
            <label class="control-label" for="inputMajor">Majors <i class="icon-star"> </i></label>
            <div class="controls">
              <input type="text" id="inputMajor" name="majors" placeholder="Enter your majors">
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend style="text-align:left">Internships</legend>
        <div class="control-group">
          <label class="control-label" for="inputPeriod">Internship <i class="icon-calendar"> </i></label>
          <div id="internship">
            <div class="control-group">
              <div class="controls">
                <input class="datepicker" type="text" id="datepicker_from" placeholder="Enter a starting date"/>
              </div>
              <label class="control-label to_label" for="inputPeriod">to</label>
              <div class="controls">
                <input class="datepicker" type="text" id="datepicker_to" placeholder="Enter an ending date"/>
              </div>
              <div class="controls">
                 <a class="btn-small btn-link internship_plus"><i class="icon-plus-sign"></i></a>
              </div>
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend style="text-align:left"></legend>
        <div class="control-group">
          <label class="control-label" for="inputKeywords">Keywords <i class="icon-thumbs-up"> </i></label>
          <div class="controls">
            <input type="text" id="inputKeywords" placeholder="Enter your keywords">
          </div>
        </div>
      </fieldset>

    </div>


    <div style="float: right; display:none">
      <input type="submit" id="save_button" class="btn btn-primary btn-large" value="Save">
    </div>


  </form>
</div>

{% endblock %}

templates/student/student_edit.html
{% extends "main.html" %}

{% block title %}
Profile
{% endblock%}

{% block content %}
<!-- <form action="/student/{{ student.id }}/save/" method="post">{% csrf_token %} -->
<!-- {{ form.as_p }} -->
<!-- <input type="submit" value="Submit" /> -->
<!-- </form> -->

<div align="center">
  <h3>
    <span style="font-weight: normal;">
      Welcome {{ student.first_name }}!
    </span>
  </h3>

  <div id="spoiler_container">
    <a id="landing_fb_connect" class="btn btn-primary btn-large" href="#">
      Use My Facebook Profile
    </a>

    <div id="spoiler_bottom">
      or
      <div id="enter_manually_div">
        <a href="#" id="enter_info_manually">
          enter your info manually
        </a>
      </div>

      <div style="text-align: center;">
        <i class="icon-chevron-down"></i>
      </div>

    </div>

  </div> <!-- end spoiler  -->

  <div id="main_form" style="display: none;">
    <form action="/student/save/" method="post" class="form-horizontal">
      {% csrf_token %}
      <input id="id_facebook_id" type="hidden" name="facebook_id" value="{{ student.facebook_id }}" />
      <div class="control-group">
        <label class="control-label" for="inputSchool">School</label>
        <div class="controls">
          <input type="text" id="inputSchool" placeholder="Enter your school">
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="inputMajor">Major</label>
        <div class="controls">
          <input type="text" id="inputMajor" placeholder="Enter your majors">
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="inputPeriod">From</label>
        <div class="controls">
          <input type="text" id="datepicker_from" placeholder="Enter a starting date"/>
        </div>
        <label class="control-label to_label" for="inputPeriod">to</label>
        <div class="controls">
          <input type="text" id="datepicker_to" placeholder="Enter an ending date"/>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="inputKeywords">Keywords</label>
        <div class="controls">
          <input type="text" id="inputKeywords" placeholder="Enter your keywords">
        </div>
      </div>

    </form>
  </div>
</div>

<div style="float: right">
  <a id="save_button" class="btn btn-primary btn-large" href="#" style="display: none;">
    Save
  </a>
</div>
{% endblock %}